#!/bin/bash

set -eu

build-base-image() {
    local tmpfs_build=$1

    echo "Updating base Docker image"

    rm -rf docker-deps
    mkdir -p docker-deps

    #
    # Image hashes taken from:
    #
    # https://hub.docker.com/_/centos?tab=tags&page=1&ordering=last_updated
    #
    case $(uname -p) in
	x86_64)
	    BASE_IMAGE=c2f1d5a9c0a81350fa0ad7e1eee99e379d75fe53823d44b5469eb2eb6092c941
	    ;;
	aarch64)
	    BASE_IMAGE=43964203bf5d7fe38c6fca6166ac89e4c095e2b0c0a28f6c7c678a1348ddc7fa
	    ;;
	*)
	    echo "Architecture not supported"
	    ;;
    esac

    cp -a docker-deps-base/epel-7-with-local-deps.cfg docker-deps/epel-7-with-local-deps.cfg

    sed -i docker-deps/epel-7-with-local-deps.cfg -e 's/x86_64/'$(uname -p)'/g'

    if [[ $tmpfs_build == "1" ]] ; then
	echo Enabling tmpfs build

	echo """
config_opts['plugin_conf']['tmpfs_enable'] = True
config_opts['plugin_conf']['tmpfs_opts'] = {}
config_opts['plugin_conf']['tmpfs_opts']['required_ram_mb'] = 128000
config_opts['plugin_conf']['tmpfs_opts']['max_fs_size'] = '40g'
config_opts['plugin_conf']['tmpfs_opts']['mode'] = '0755'
config_opts['plugin_conf']['tmpfs_opts']['keep_mounted'] = True
	""" >> docker-deps/epel-7-with-local-deps.cfg
    fi

    echo """
# CentOS 7

FROM centos@sha256:${BASE_IMAGE}

RUN rm -f /root/*.cfg
RUN mkdir /workspace

RUN yum install -y epel-release sudo
RUN yum install -y fedpkg createrepo wget

ADD epel-7-with-local-deps.cfg /etc/mock/epel-7-with-local-deps.cfg
RUN mkdir -p /opt/repo/epel-7-with-local-deps
RUN createrepo /opt/repo/epel-7-with-local-deps
""" > Dockerfile

    docker build -f Dockerfile -t llvm-rpm:base docker-deps/
    rm -f Dockerfile

    docker rm -f llvm-rpm-modified 2>/dev/null || true

    docker run --name llvm-rpm-modified -it --privileged llvm-rpm:base \
	mock --init --root epel-7-with-local-deps
    docker commit llvm-rpm-modified llvm-rpm:init
    docker rm -f llvm-rpm-modified 2>/dev/null

    rm -rf docker-deps/
}

spin-up-instance() {
    docker rm -f llvm-rpm-run 2>/dev/null || true
    mkdir -p ${PWD}/repo
    docker run --rm -dit --name llvm-rpm-run --privileged -w /workspace -v /tmp:/tmp \
	-v ${PWD}/repo:/opt/repo/epel-7-with-local-deps -v ${PWD}:/workspace llvm-rpm:init bash
}

run-build() {
    docker exec -it llvm-rpm-run ./run.sh
}

pkgbuild() {
    echo "Building $1"

    local dest=/opt/repo/epel-7-with-local-deps
    local name=$1
    cd pkgs/${name}
    shift

    while [[ $# != 0 ]] ; do
        if [[ "$1" == "--name" ]] ; then
	    shift
	    local name=$1
            shift
            continue
        fi
        break
    done

    rm -rf *.src.rpm
    rm -rf results_${name}*
    fedpkg --name ${name} --release el7 mockbuild --root epel-7-with-local-deps "$@"
    rm -rf ${dest}/results_${name}
    mv results_${name} ${dest}
    createrepo ${dest}
    cd ../..
}

under-container() {
    local skip_build_image=0
    local skip_spin_up_instance=0
    local tmpfs_build=0

    while [[ $# != 0 ]] ; do
        if [[ "$1" == "--skip-build-base-image" ]] || [[ "$1" == "-s" ]] ; then
	    local skip_build_image=1
            shift
            continue
        fi
        if [[ "$1" == "--skip-spin-up-image" ]] || [[ "$1" == "-r" ]] ; then
	    local skip_spin_up_instance=1
            shift
            continue
        fi
        if [[ "$1" == "--tmpfs-build" ]] || [[ "$1" == "-t" ]] ; then
	    local tmpfs_build=1
            shift
            continue
        fi
        if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]] ; then
	    echo "--skip-build-base-image   -s"
	    echo "--skip-spin-up-image      -r"
	    echo "--tmpfs-build             -t"
	    exit 0
        fi
        break
    done

    if [[ "${skip_build_image}" == "0" ]] ; then
	build-base-image ${tmpfs_build}
    fi

    if [[ "${skip_spin_up_instance}" == "0" ]] ; then
	spin-up-instance
    fi

    docker exec -it llvm-rpm-run ./run run-inside-instance "$@"
}

run-inside-instance() {
    "$@"
}

stage0() {
    pkgbuild cmake --without test --with bootstrap
}

stage1() {
    local commit=$(grep 'global gitcommit' \
	pkgs/llvm-monolith/llvm.spec  | awk -F" " '{print $3}')
    if [[ ! -e pkgs/llvm-monolith/${commit}.tar.gz ]] ; then
	wget https://github.com/llvm/llvm-project/archive/${commit}.tar.gz -O \
	    pkgs/llvm-monolith/${commit}.tar.gz.tmp
	mv pkgs/llvm-monolith/${commit}.tar.gz.tmp pkgs/llvm-monolith/${commit}.tar.gz
    fi
    pkgbuild llvm-monolith --name llvm-11.1.0 --with bootstrap
}

stage2() {
    pkgbuild llvm --with stage1
    pkgbuild clang --without python3 --with stage1 --with static_link
    pkgbuild python-lit --without check
    pkgbuild compiler-rt --with bootstrap --with stage1
    pkgbuild libcxx --with bootstrap --with stage1
    pkgbuild libcxxabi --with stage1
    pkgbuild lld --with stage1
}

stage3() {
    pkgbuild libcxx
    pkgbuild lld --with stage2
}

build-all() {
    stage0
    stage1
    stage2
    stage3
}

"$@"
